#!/bin/bash
echo "📊 ANALYSE DU FLUX D'EXTRACTION:"
echo ""
echo "1. MainActivity - startVoiceServices() est appelé à CHAQUE onCreate()"
echo "2. ModelDownloadService - extractVoskModels() vérifie isModelExtracted()"
echo "3. SI isModelExtracted() = TRUE → extraction sautée"
echo "4. MAIS le broadcast est envoyé QUAND MÊME ?"
echo ""
echo "🔍 REGARDEZ ModelDownloadService.kt:"
echo "   - La méthode extractVoskModels() retourne 'allSuccess'"
echo "   - Si modèles déjà extraits, allSuccess = true"
echo "   - Donc broadcast SUCCESS envoyé même sans extraction"
echo ""
echo "🎯 PROBLÈME IDENTIFIÉ:"
echo "   Le service envoie 'success=true' même quand l'extraction était déjà faite"
echo "   Ce qui déclenche le popup à chaque fois"
