#!/bin/bash
echo "📱 Instructions pour debugger le crash :"
echo ""
echo "1. INSTALLER l'APK sur ton téléphone"
echo "2. OUVREZ l'application" 
echo "3. CONNECTEZ le téléphone en debug USB"
echo "4. EXÉCUTEZ : adb logcat | grep -i magiccontrol"
echo ""
echo "5. OU capturez les logs via Termux :"
echo "   logcat -d | grep -i magiccontrol > crash_log.txt"
echo ""
echo "📋 Les causes probables :"
echo "- Permissions manquantes"
echo"- Service Accessibility non configuré"
echo "- Modèles Vosk non chargés"
echo "- Configuration AndroidManifest"
